// Code generated by lattice-server tools/tsgen from the server's JSON tags. DO NOT EDIT.
//
// A field marked optional is omitted when empty; one typed `| null` is
// always present and may be null. Times are RFC 3339 strings.

export interface BindEntry {
  index: number;
  line_uuid?: string;
  provider?: boolean;
  name?: string;
  label?: string;
  node_id?: string;
  protocol?: string;
  server?: string;
  port?: number;
  clone?: number;
  digest: string;
}

export interface BindExclusion {
  index: number;
  line_uuid?: string;
  name?: string;
  reason: string;
  fix?: string;
  detail?: string;
}

export interface BindPreviewReply {
  subscription_id: string;
  revision?: string;
  identity_id: string;
  identity_status: string;
  kind: string;
  source_version?: string;
  live_revision?: string;
  entries: BindEntry[];
  excluded: BindExclusion[];
  refused?: string;
  fleet_nodes: number;
}

export interface PlanStatusRow {
  approval_id: string;
  status: string;
  reason?: string;
  plan_sha256: string;
  subscription_id: string;
  from_revision: string;
  to_revision: string;
  actor_id?: string;
  approved_by?: string;
  created_at: string;
  updated_at: string;
}

export interface PlansProposeReply {
  required: boolean;
  reason?: string;
  approval_id?: string;
  plan_sha256?: string;
  plan?: string;
  status?: string;
}

export interface PlanTotals {
  shares: number;
  unbound_shares: number;
  identities: number;
  added: number;
  removed: number;
  changed: number;
  excluded: number;
}

export interface PlanShare {
  share_id: string;
  slug: string;
  display_name?: string;
  identity_id: string;
  enabled: boolean;
  expires_at?: string;
  added: number;
  removed: number;
  changed: number;
  excluded: number;
}

export interface PlanUnboundShare {
  share_id: string;
  slug: string;
  display_name?: string;
  enabled: boolean;
  expires_at?: string;
  fleet_credentials: boolean;
}

export interface PlanLine {
  line_uuid: string;
  names: string[];
  digest: string;
  reason?: string;
}

export interface PlanLineState {
  names: string[];
  digest: string;
}

export interface PlanLineChange {
  line_uuid: string;
  before: PlanLineState;
  after: PlanLineState;
}

export interface BindLine {
  line_uuid?: string;
  name?: string;
  reason?: string;
}

export interface PlanIdentity {
  identity_id: string;
  added: PlanLine[];
  removed: PlanLine[];
  changed: PlanLineChange[];
  excluded: BindLine[];
  unchanged: number;
}

export interface Plan {
  kind: string;
  plugin_id: string;
  subscription_id: string;
  from_revision: string;
  to_revision: string;
  totals: PlanTotals;
  shares: PlanShare[];
  unbound_shares: PlanUnboundShare[];
  coverage?: string;
  identities: PlanIdentity[];
}

export interface ShareIcon {
  url: string;
  color?: string;
  fit?: string;
}

export interface ShareRow {
  subscription_id: string;
  share_id: string;
  slug: string;
  enabled: boolean;
  default_format?: string;
  expires_at?: string;
  path: string;
  url?: string;
  revealed?: boolean;
  display_name?: string;
  remark?: string;
  icon?: ShareIcon;
  tags?: string[];
  order: number;
  archived_at?: string;
  identity_id?: string;
  update_interval_hours: number;
  age_recipient?: string;
  created_at: string;
  updated_at: string;
  rotated_at?: string;
}
