// Command tsgen writes the TypeScript declarations of the core replies the
// Sub-Store UI reads (design 28 S2): the bind preview, its entries and
// exclusions, the plan status row, the plan proposal and the plan itself,
// and the shares list entry. It reads the Go source of internal/server and
// of the SDK's model package and follows each field's JSON tag, so the UI's
// types are the server's wire, not a hand copy of it: a hand copy is how an
// earlier draft lost label, node_id and clone.
//
//	go run ./tools/tsgen -ref <server commit> -o core-types.ts
//
// The UI commits the output as ui/src/core-types.ts, and its contract test
// regenerates it at the pinned server commit and compares.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
)

// roots are the replies the UI reads, by Go type name, with the TypeScript
// name each is published under, in output order.
var roots = []struct{ goName, tsName string }{
	{"substoreBindPreviewReply", "BindPreviewReply"},
	{"substoreBindEntry", "BindEntry"},
	{"substoreBindExclusion", "BindExclusion"},
	{"subStorePlanStatusRow", "PlanStatusRow"},
	{"subStorePlansProposeReply", "PlansProposeReply"},
	{"subStorePlan", "Plan"},
	{"subStoreShareRow", "ShareRow"},
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("tsgen", flag.ContinueOnError)
	flags.SetOutput(stderr)
	serverDir := flags.String("server", "internal/server", "directory of the server package")
	sdkDir := flags.String("sdk", "", "directory of the SDK module (default: go list -m github.com/LatticeNet/lattice-sdk)")
	ref := flags.String("ref", "", "the server commit the declarations are generated from, written in the header")
	out := flags.String("o", "", "output file (default: stdout)")
	if err := flags.Parse(args); err != nil {
		return 2
	}
	if *sdkDir == "" {
		dir, err := sdkModuleDir()
		if err != nil {
			fmt.Fprintln(stderr, "tsgen:", err)
			return 1
		}
		*sdkDir = dir
	}
	source, err := generate(*serverDir, filepath.Join(*sdkDir, "model"), *ref)
	if err != nil {
		fmt.Fprintln(stderr, "tsgen:", err)
		return 1
	}
	if *out == "" {
		_, err = stdout.Write(source)
	} else {
		err = os.WriteFile(*out, source, 0o644)
	}
	if err != nil {
		fmt.Fprintln(stderr, "tsgen:", err)
		return 1
	}
	return 0
}

// sdkModuleDir is where the go command keeps the SDK module this server
// requires.
func sdkModuleDir() (string, error) {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/LatticeNet/lattice-sdk").Output()
	if err != nil {
		return "", fmt.Errorf("locate the sdk module: %w", err)
	}
	dir := strings.TrimSpace(string(out))
	if dir == "" {
		return "", errors.New("locate the sdk module: go list printed no directory")
	}
	return dir, nil
}

// pkg is the struct and named types of one parsed package.
type pkg struct {
	types map[string]ast.Expr
}

func parsePackage(dir string) (*pkg, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	out := &pkg{types: map[string]ast.Expr{}}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, err
		}
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts := spec.(*ast.TypeSpec)
				if ts.TypeParams == nil {
					out.types[ts.Name.Name] = ts.Type
				}
			}
		}
	}
	return out, nil
}

// generator walks the root types and every type they reach.
type generator struct {
	server, model *pkg
	// names maps a type's key ("server.x" or "model.X") to its TypeScript
	// name; order is the order declarations are written.
	names map[string]string
	order []string
	decls map[string]string
}

func generate(serverDir, modelDir, ref string) ([]byte, error) {
	server, err := parsePackage(serverDir)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", serverDir, err)
	}
	model, err := parsePackage(modelDir)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", modelDir, err)
	}
	g := &generator{server: server, model: model, names: map[string]string{}, decls: map[string]string{}}
	for _, root := range roots {
		g.names["server."+root.goName] = root.tsName
	}
	for _, root := range roots {
		if _, err := g.named("server", root.goName); err != nil {
			return nil, err
		}
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by lattice-server tools/tsgen from the server's JSON tags. DO NOT EDIT.\n")
	if ref != "" {
		b.WriteString("// Source: lattice-server " + ref + "\n")
	}
	b.WriteString("//\n")
	b.WriteString("// A field marked optional is omitted when empty; one typed `| null` is\n")
	b.WriteString("// always present and may be null. Times are RFC 3339 strings.\n")
	for _, key := range g.order {
		b.WriteString("\n")
		b.WriteString(g.decls[key])
	}
	return b.Bytes(), nil
}

// tsName is the TypeScript name of a type outside the roots: the Go name
// with the package prefixes dropped and the first letter upper-cased.
func tsName(goName string) string {
	for _, prefix := range []string{"substore", "subStore"} {
		if rest, ok := strings.CutPrefix(goName, prefix); ok && rest != "" {
			goName = rest
			break
		}
	}
	return strings.ToUpper(goName[:1]) + goName[1:]
}

// named declares a named type of pkgName once and returns its TypeScript
// name, or, for a named type over a basic one, the basic TypeScript type.
func (g *generator) named(pkgName, goName string) (string, error) {
	key := pkgName + "." + goName
	if name, ok := g.names[key]; ok {
		if _, declared := g.decls[key]; declared || g.inProgress(key) {
			return name, nil
		}
	}
	p := g.server
	if pkgName == "model" {
		p = g.model
	}
	expr, ok := p.types[goName]
	if !ok {
		return "", fmt.Errorf("type %s not found", key)
	}
	st, isStruct := expr.(*ast.StructType)
	if !isStruct {
		return g.expr(pkgName, expr)
	}
	name, ok := g.names[key]
	if !ok {
		name = tsName(goName)
		for other, taken := range g.names {
			if taken == name {
				return "", fmt.Errorf("%s and %s would both be published as %s", other, key, name)
			}
		}
		g.names[key] = name
	}
	g.decls[key] = "" // in progress
	var fields []string
	if err := g.fields(pkgName, st, &fields); err != nil {
		return "", fmt.Errorf("%s: %w", key, err)
	}
	var b strings.Builder
	b.WriteString("export interface " + name + " {\n")
	for _, field := range fields {
		b.WriteString("  " + field + ";\n")
	}
	b.WriteString("}\n")
	g.decls[key] = b.String()
	g.order = append(g.order, key)
	return name, nil
}

func (g *generator) inProgress(key string) bool {
	decl, ok := g.decls[key]
	return ok && decl == ""
}

// fields writes a struct's JSON fields, inlining an embedded struct that
// carries no tag, as encoding/json does.
func (g *generator) fields(pkgName string, st *ast.StructType, out *[]string) error {
	for _, field := range st.Fields.List {
		tag := ""
		if field.Tag != nil {
			unquoted, err := strconv.Unquote(field.Tag.Value)
			if err != nil {
				return err
			}
			tag = reflect.StructTag(unquoted).Get("json")
		}
		name, opts, _ := strings.Cut(tag, ",")
		if name == "-" && opts == "" {
			continue
		}
		omit := strings.Contains(","+opts+",", ",omitempty,") || strings.Contains(","+opts+",", ",omitzero,")
		if len(field.Names) == 0 {
			ident, ok := field.Type.(*ast.Ident)
			if !ok {
				return fmt.Errorf("embedded field of type %T is not supported", field.Type)
			}
			if tag == "" {
				embedded, ok := g.server.types[ident.Name]
				if pkgName == "model" {
					embedded, ok = g.model.types[ident.Name]
				}
				st, isStruct := embedded.(*ast.StructType)
				if !ok || !isStruct {
					return fmt.Errorf("embedded %s is not a struct", ident.Name)
				}
				if err := g.fields(pkgName, st, out); err != nil {
					return err
				}
				continue
			}
			field.Names = []*ast.Ident{ident}
		}
		for _, ident := range field.Names {
			if !ident.IsExported() {
				continue
			}
			jsonName := name
			if jsonName == "" {
				jsonName = ident.Name
			}
			ts, err := g.expr(pkgName, field.Type)
			if err != nil {
				return fmt.Errorf("field %s: %w", ident.Name, err)
			}
			_, pointer := field.Type.(*ast.StarExpr)
			switch {
			case omit:
				*out = append(*out, quoteKey(jsonName)+"?: "+ts)
			case pointer:
				*out = append(*out, quoteKey(jsonName)+": "+ts+" | null")
			default:
				*out = append(*out, quoteKey(jsonName)+": "+ts)
			}
		}
	}
	return nil
}

func quoteKey(name string) string {
	for i, r := range name {
		if !(r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9')) {
			return strconv.Quote(name)
		}
	}
	return name
}

// expr is the TypeScript type of a Go type expression in pkgName.
func (g *generator) expr(pkgName string, expr ast.Expr) (string, error) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return "string", nil
		case "bool":
			return "boolean", nil
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
			return "number", nil
		case "any":
			return "unknown", nil
		}
		return g.named(pkgName, t.Name)
	case *ast.StarExpr:
		return g.expr(pkgName, t.X)
	case *ast.ArrayType:
		if ident, ok := t.Elt.(*ast.Ident); ok && ident.Name == "byte" {
			return "string", nil // base64, as encoding/json writes []byte
		}
		elem, err := g.expr(pkgName, t.Elt)
		if err != nil {
			return "", err
		}
		if strings.Contains(elem, " ") {
			elem = "(" + elem + ")"
		}
		return elem + "[]", nil
	case *ast.MapType:
		value, err := g.expr(pkgName, t.Value)
		if err != nil {
			return "", err
		}
		return "Record<string, " + value + ">", nil
	case *ast.SelectorExpr:
		x, ok := t.X.(*ast.Ident)
		if !ok {
			return "", fmt.Errorf("unsupported selector %T", t.X)
		}
		switch x.Name + "." + t.Sel.Name {
		case "time.Time":
			return "string", nil
		case "json.RawMessage":
			return "unknown", nil
		}
		if x.Name == "model" {
			return g.named("model", t.Sel.Name)
		}
		return "", fmt.Errorf("unsupported type %s.%s", x.Name, t.Sel.Name)
	case *ast.InterfaceType:
		return "unknown", nil
	}
	return "", fmt.Errorf("unsupported type expression %T", expr)
}
