package auth

import (
	"crypto/sha256"
	"encoding/hex"
	"time"
)

// OIDCAuthState is the short-lived, single-use state for one in-flight OIDC
// auth-code login. It is created at /start, persisted, and consumed at
// /callback. It binds the round trip together:
//   - State: the OAuth2 `state` parameter (CSRF defense; also the store key).
//   - Nonce: checked against the ID token `nonce` claim (replay defense).
//   - CodeVerifier: the PKCE verifier (binds the code to this client).
//   - ClientIP: the requester's IP; the callback must come from the same IP.
//   - RedirectAfter: a sanitized same-origin path to land on after login.
type OIDCAuthState struct {
	State         string `json:"state"`
	Nonce         string `json:"nonce"`
	CodeVerifier  string `json:"code_verifier"`
	ProviderID    string `json:"provider_id"`
	ClientIP      string `json:"client_ip"`
	RedirectAfter string `json:"redirect_after"`
	// BindingHash is the SHA-256 (hex) of a per-flow token set as an HttpOnly
	// cookie at /start; the callback must present the matching cookie. This
	// binds the round trip to the initiating browser (login-CSRF defense), the
	// spec-intended role of `state`. Only the hash is persisted.
	BindingHash string    `json:"binding_hash"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
}

// NewOIDCAuthState mints state with fresh random `state` and `nonce` values, the
// caller-supplied PKCE verifier (generated by the oidc layer via
// oauth2.GenerateVerifier so this package stays dependency-free), and the SHA-256
// of the caller-supplied browser-binding token.
func NewOIDCAuthState(providerID, clientIP, redirectAfter, codeVerifier, bindingToken string, ttl time.Duration) (OIDCAuthState, error) {
	state, err := NewRandomToken(32)
	if err != nil {
		return OIDCAuthState{}, err
	}
	nonce, err := NewRandomToken(32)
	if err != nil {
		return OIDCAuthState{}, err
	}
	now := time.Now().UTC()
	return OIDCAuthState{
		State:         state,
		Nonce:         nonce,
		CodeVerifier:  codeVerifier,
		ProviderID:    providerID,
		ClientIP:      clientIP,
		RedirectAfter: redirectAfter,
		BindingHash:   HashBindingToken(bindingToken),
		CreatedAt:     now,
		ExpiresAt:     now.Add(ttl),
	}, nil
}

// HashBindingToken returns the hex SHA-256 of a browser-binding token. The
// callback hashes the presented cookie and compares it to the stored hash.
func HashBindingToken(token string) string {
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}

// Expired reports whether the state has passed its TTL.
func (s OIDCAuthState) Expired() bool {
	return time.Now().UTC().After(s.ExpiresAt)
}
